// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnByD24J_MPtA5E2zHVqvEY8leIqZ9i8Q',
    appId: '1:971717002090:web:0e66758fed90d5fd921b13',
    messagingSenderId: '971717002090',
    projectId: 'proj-flutter-2f30b',
    authDomain: 'proj-flutter-2f30b.firebaseapp.com',
    storageBucket: 'proj-flutter-2f30b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjrGtg2FciCfefpFwCUK-ctLVdIbtODzk',
    appId: '1:971717002090:android:0e3b74086deaf005921b13',
    messagingSenderId: '971717002090',
    projectId: 'proj-flutter-2f30b',
    storageBucket: 'proj-flutter-2f30b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFZDXdFdlvPU686r0J6vqx99OlW-a-L7s',
    appId: '1:971717002090:ios:f09c295c40299c96921b13',
    messagingSenderId: '971717002090',
    projectId: 'proj-flutter-2f30b',
    storageBucket: 'proj-flutter-2f30b.appspot.com',
    iosBundleId: 'br.pro.aguiar.projDesenvFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFZDXdFdlvPU686r0J6vqx99OlW-a-L7s',
    appId: '1:971717002090:ios:f09c295c40299c96921b13',
    messagingSenderId: '971717002090',
    projectId: 'proj-flutter-2f30b',
    storageBucket: 'proj-flutter-2f30b.appspot.com',
    iosBundleId: 'br.pro.aguiar.projDesenvFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnByD24J_MPtA5E2zHVqvEY8leIqZ9i8Q',
    appId: '1:971717002090:web:434331ab11f3816b921b13',
    messagingSenderId: '971717002090',
    projectId: 'proj-flutter-2f30b',
    authDomain: 'proj-flutter-2f30b.firebaseapp.com',
    storageBucket: 'proj-flutter-2f30b.appspot.com',
  );
}
